# Generated by Django 3.2 on 2024-11-02 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='部门名称')),
                ('index', models.IntegerField(blank=True, null=True, verbose_name='排序')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('job_number', models.CharField(max_length=50, verbose_name='工号')),
                ('gender', models.IntegerField(blank=True, choices=[(1, '男'), (2, '女')], default=1, null=True, verbose_name='性别')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='出生日期')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='手机号码')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='邮箱')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='家庭住址')),
                ('nation', models.CharField(blank=True, max_length=50, null=True, verbose_name='民族')),
                ('marital', models.IntegerField(blank=True, choices=[(1, '已婚'), (2, '未婚')], default=2, null=True, verbose_name='婚姻状况')),
                ('id_number', models.CharField(blank=True, max_length=18, null=True, verbose_name='身份证号')),
                ('hiredate', models.DateField(verbose_name='入职日期')),
                ('rank', models.CharField(blank=True, max_length=50, null=True, verbose_name='职级')),
                ('depart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.department', verbose_name='部门')),
            ],
        ),
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('relationship', models.IntegerField(choices=[(1, '父子'), (2, '母子'), (3, '兄弟姐妹'), (4, '其他')], verbose_name='家人关系')),
                ('phone', models.CharField(max_length=11, verbose_name='手机号码')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='家庭住址')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.employee', verbose_name='员工ID')),
            ],
        ),
    ]
