# Generated by Django 3.2 on 2024-11-03 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_dep'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dep',
        ),
    ]
