# Generated by Django 3.2 on 2024-11-10 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app01', '0003_delete_dep'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='角色名称')),
                ('remark', models.CharField(blank=True, max_length=255, null=True, verbose_name='备注')),
            ],
            options={
                'db_table': 'sys_role',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, verbose_name='用户账号')),
                ('password', models.CharField(max_length=40, verbose_name='用户密码')),
                ('avatarUrl', models.CharField(blank=True, max_length=250, null=True, verbose_name='头像')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='最后登录时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app01.employee', verbose_name='员工ID')),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='userinfo.role', verbose_name='角色')),
            ],
            options={
                'db_table': 'sys_user',
            },
        ),
    ]
